// Code generated by protoc-gen-go.
// source: tracer.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	tracer.proto

It has these top-level messages:
	Trace
	Span
	Tag
	StoreRequest
	StoreResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Trace struct {
}

func (m *Trace) Reset()                    { *m = Trace{} }
func (m *Trace) String() string            { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()               {}
func (*Trace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Span struct {
	SpanId        uint64                     `protobuf:"varint,1,opt,name=span_id,json=spanId" json:"span_id,omitempty"`
	ParentId      uint64                     `protobuf:"varint,2,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	TraceId       uint64                     `protobuf:"varint,3,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
	ServiceName   string                     `protobuf:"bytes,4,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	OperationName string                     `protobuf:"bytes,5,opt,name=operation_name,json=operationName" json:"operation_name,omitempty"`
	StartTime     *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	FinishTime    *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=finish_time,json=finishTime" json:"finish_time,omitempty"`
	Flags         uint64                     `protobuf:"varint,8,opt,name=flags" json:"flags,omitempty"`
	Tags          []*Tag                     `protobuf:"bytes,9,rep,name=tags" json:"tags,omitempty"`
}

func (m *Span) Reset()                    { *m = Span{} }
func (m *Span) String() string            { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()               {}
func (*Span) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Span) GetStartTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Span) GetFinishTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.FinishTime
	}
	return nil
}

func (m *Span) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Tag struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	// FIXME support non-string values
	Value string                     `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Time  *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Tag) GetTime() *google_protobuf.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type StoreRequest struct {
	Spans []*Span `protobuf:"bytes,1,rep,name=spans" json:"spans,omitempty"`
}

func (m *StoreRequest) Reset()                    { *m = StoreRequest{} }
func (m *StoreRequest) String() string            { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()               {}
func (*StoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StoreRequest) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type StoreResponse struct {
}

func (m *StoreResponse) Reset()                    { *m = StoreResponse{} }
func (m *StoreResponse) String() string            { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()               {}
func (*StoreResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Trace)(nil), "pb.Trace")
	proto.RegisterType((*Span)(nil), "pb.Span")
	proto.RegisterType((*Tag)(nil), "pb.Tag")
	proto.RegisterType((*StoreRequest)(nil), "pb.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "pb.StoreResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Storer service

type StorerClient interface {
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
}

type storerClient struct {
	cc *grpc.ClientConn
}

func NewStorerClient(cc *grpc.ClientConn) StorerClient {
	return &storerClient{cc}
}

func (c *storerClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := grpc.Invoke(ctx, "/pb.Storer/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Storer service

type StorerServer interface {
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
}

func RegisterStorerServer(s *grpc.Server, srv StorerServer) {
	s.RegisterService(&_Storer_serviceDesc, srv)
}

func _Storer_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorerServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Storer/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorerServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Storer",
	HandlerType: (*StorerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Storer_Store_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("tracer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x51, 0xcd, 0x6a, 0x1b, 0x31,
	0x10, 0x66, 0xbd, 0xbb, 0x5e, 0xef, 0xd8, 0x69, 0x53, 0x51, 0xe8, 0xd6, 0x81, 0xe2, 0x2e, 0x14,
	0x7c, 0x28, 0x32, 0xb8, 0x50, 0x28, 0x79, 0x02, 0x5f, 0x7a, 0x50, 0x7c, 0x2d, 0x46, 0x6b, 0x8f,
	0x95, 0xa5, 0x5e, 0x49, 0x95, 0xe4, 0x40, 0xde, 0xb1, 0x0f, 0x55, 0x34, 0x4a, 0x9a, 0xdc, 0x7c,
	0x9b, 0xef, 0x6f, 0xf8, 0x46, 0x82, 0x59, 0x70, 0x72, 0x8f, 0x8e, 0x5b, 0x67, 0x82, 0x61, 0x23,
	0xdb, 0xcd, 0x6f, 0x55, 0x1f, 0xee, 0xcf, 0x1d, 0xdf, 0x9b, 0x61, 0xa5, 0xcc, 0x49, 0x6a, 0xb5,
	0x22, 0xb1, 0x3b, 0x1f, 0x57, 0x36, 0x3c, 0x5a, 0xf4, 0xab, 0xd0, 0x0f, 0xe8, 0x83, 0x1c, 0xec,
	0xcb, 0x94, 0x16, 0xb4, 0x15, 0x94, 0xdb, 0xb8, 0xb0, 0xfd, 0x3b, 0x82, 0xe2, 0xce, 0x4a, 0xcd,
	0x3e, 0x40, 0xe5, 0xad, 0xd4, 0xbb, 0xfe, 0xd0, 0x64, 0x8b, 0x6c, 0x59, 0x88, 0x71, 0x84, 0x9b,
	0x03, 0xbb, 0x81, 0xda, 0x4a, 0x87, 0x3a, 0x44, 0x69, 0x44, 0xd2, 0x24, 0x11, 0x9b, 0x03, 0xfb,
	0x08, 0x13, 0x2a, 0x16, 0xb5, 0x9c, 0xb4, 0x8a, 0xf0, 0xe6, 0xc0, 0x3e, 0xc3, 0xcc, 0xa3, 0x7b,
	0xe8, 0xf7, 0xb8, 0xd3, 0x72, 0xc0, 0xa6, 0x58, 0x64, 0xcb, 0x5a, 0x4c, 0x9f, 0xb8, 0x9f, 0x72,
	0x40, 0xf6, 0x05, 0xde, 0x18, 0x8b, 0x4e, 0x86, 0xde, 0xe8, 0x64, 0x2a, 0xc9, 0x74, 0xf5, 0x9f,
	0x25, 0xdb, 0x0f, 0x00, 0x1f, 0xa4, 0x0b, 0xbb, 0x78, 0x45, 0x33, 0x5e, 0x64, 0xcb, 0xe9, 0x7a,
	0xce, 0x95, 0x31, 0xea, 0x84, 0xfc, 0xf9, 0x66, 0xbe, 0x7d, 0x3e, 0x51, 0xd4, 0xe4, 0x8e, 0x98,
	0xdd, 0xc2, 0xf4, 0xd8, 0xeb, 0xde, 0xdf, 0xa7, 0x6c, 0x75, 0x31, 0x0b, 0xc9, 0x4e, 0xe1, 0xf7,
	0x50, 0x1e, 0x4f, 0x52, 0xf9, 0x66, 0x42, 0x97, 0x25, 0xc0, 0x6e, 0xa0, 0x08, 0x91, 0xac, 0x17,
	0xf9, 0x72, 0xba, 0xae, 0xb8, 0xed, 0xf8, 0x56, 0x2a, 0x41, 0x64, 0xfb, 0x0b, 0xf2, 0xad, 0x54,
	0xec, 0x1a, 0xf2, 0xdf, 0xf8, 0x48, 0x0f, 0x59, 0x8b, 0x38, 0xc6, 0x5d, 0x0f, 0xf2, 0x74, 0x46,
	0x7a, 0xc1, 0x5a, 0x24, 0xc0, 0x38, 0x14, 0xd4, 0x2b, 0xbf, 0xd8, 0x8b, 0x7c, 0x2d, 0x87, 0xd9,
	0x5d, 0x30, 0x0e, 0x05, 0xfe, 0x39, 0xa3, 0x0f, 0xec, 0x13, 0x94, 0xf1, 0x97, 0x7c, 0x93, 0x51,
	0x99, 0x49, 0x2c, 0x13, 0x7f, 0x53, 0x24, 0xba, 0x7d, 0x0b, 0x57, 0x4f, 0x7e, 0x6f, 0x8d, 0xf6,
	0xb8, 0xfe, 0x0e, 0x63, 0x22, 0x1c, 0xfb, 0x0a, 0x25, 0x4d, 0xec, 0x9a, 0x42, 0xaf, 0xb6, 0xce,
	0xdf, 0xbd, 0x62, 0x52, 0xae, 0x1b, 0x53, 0xa5, 0x6f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbb,
	0xba, 0x7b, 0xfc, 0x87, 0x02, 0x00, 0x00,
}
